language: node_js
node_js:
  - "4"
before_install:
  - gem install sass
script:
  - ./scripts/plug_versions.coffee
  - ./scripts/get_boards.coffee production
  - ./configure.coffee production
  - wget https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-linux.zip
  - unzip ninja-linux.zip
  - ./ninja && ./scripts/deploy.sh
