language: node_js
node_js:
  - "6"
env:
  - CXX=g++-4.8
cache:
    directories:
        - build
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - inkscape
script:
  - export NODE_ENV=production
  - ./scripts/update_registry
  - ./scripts/get_boards production
  - ./configure production
  - wget https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-linux.zip
  - unzip ninja-linux.zip
  - ./ninja -j 5 && ./scripts/deploy
