language: node_js
node_js:
  - "12"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:js-reynaud/kicad-5.1'
    packages:
      - inkscape
      - kicad
script:
  - bash keep_alive.sh &
  - export NODE_ENV=production
  - ./scripts/plug_versions
  - ./scripts/get_boards production
  - ./configure production
  - wget https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-linux.zip
  - unzip ninja-linux.zip
  - ./ninja -j 2 && ./scripts/deploy
