gitlab:
  image: 'gitlab/gitlab-ce:10.6.0-ce.0'
  restart: always
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://localhost/gitlab'
      # Add any other gitlab.rb configuration here, each on its own line
  ports:
    - '8079:80'
    - '8022:22'
  volumes:
    - '/srv/gitlab/config:/etc/gitlab'
    - '/srv/gitlab/logs:/var/log/gitlab'
    - '/srv/gitlab/data:/var/opt/gitlab'
nginx:
  image: 'nginx:1.13.10-alpine'
  volumes:
    - './nginx:/etc/nginx/conf.d'
  ports:
   - '8080:80'
